/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{html,js,svelte,ts}'],
  theme: {
    extend: {
      colors: {
        "on-surface": "#191c1d",
        "on-error": "#ffffff",
        "on-surface-variant": "#3f4a3c",
        "tertiary-fixed": "#ffd9e2",
        "secondary-fixed": "#a4f0e9",
        "outline-variant": "#becab9",
        "inverse-on-surface": "#f0f1f2",
        "tertiary": "#a63360",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#ffb1c7",
        "primary": "#006e1c",
        "secondary-container": "#a4f0e9",
        "background": "#f8f9fa",
        "primary-container": "#4caf50",
        "tertiary-container": "#f26f9d",
        "primary-fixed": "#94f990",
        "surface-container-highest": "#e1e3e4",
        "on-secondary-fixed-variant": "#00504b",
        "on-tertiary-fixed": "#3e001c",
        "surface-variant": "#e1e3e4",
        "surface-container-low": "#f3f4f5",
        "on-tertiary-container": "#690034",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e7e8e9",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#002204",
        "outline": "#6f7a6b",
        "on-secondary-container": "#1d706a",
        "surface": "#f8f9fa",
        "inverse-primary": "#78dc77",
        "on-secondary-fixed": "#00201e",
        "on-secondary": "#ffffff",
        "error-container": "#ffdad6",
        "on-primary-container": "#003c0b",
        "surface-bright": "#f8f9fa",
        "secondary-fixed-dim": "#89d4cd",
        "surface-dim": "#d9dadb",
        "on-primary": "#ffffff",
        "surface-container": "#edeeef",
        "surface-tint": "#006e1c",
        "on-background": "#191c1d",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#78dc77",
        "secondary": "#136964",
        "on-tertiary-fixed-variant": "#861948",
        "on-primary-fixed-variant": "#005313",
        "inverse-surface": "#2e3132"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "1.5rem",
        "2xl": "2rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Inter"],
        "label": ["Inter"]
      }
    },
  },
  plugins: [],
}
